language: elixir
elixir:
  - 1.4.2
otp_release:
  - 19.2
install:
  - mix local.hex --force
  - mix local.rebar --force
script: "MIX_ENV=test mix do deps.get, deps.compile, test --cover"

after_script:
  - mix deps.get --only docs
