language: elixir
elixir:
  - 1.2.2
otp_release:
  - 18.2.1
install:
  - mix local.hex --force
script: "MIX_ENV=test mix do deps.get, deps.compile, test --cover"

after_script:
  - mix deps.get --only docs
